### ISSUE TITLE
Server got crash when load files

### ISSUE THREAD

**Issue by directentis1** [hffqyd/tw5-server#3]
I tried to use tw5server on Android and Linux, it got crash often if I put tiddly html files in another dictionary level.

Something like..
![image](https://github.com/user-attachments/assets/57e65ed5-c585-4e62-b81a-9d46af792fb8)

I'm not sure if it's from nim upstream?

**Comment by hffqyd** [comment]
Thanks for your feedback.
I've fixed the bug and updated a new version. Please have a try and if anything happens, please tell me.

**Comment by directentis1** [comment]
Thanks for the quick response!! I will try it right away and let you know 😊

**Comment by directentis1** [comment]
After a day of use, I found it worked stably and didn't crash anymore!! 

I think I will close this issue here.

Just one additional question: if I have many tiddlywiki html files in subpaths in the directory tree from the root directory of tw5-server up, how should the backup of these files be handled?

**Comment by hffqyd** [comment]
Thanks for your test.

As for the second question, all backups of tiddlywiki html files are saved in the backup dir of the root path currently. So if two different wiki files had the same name AND were saved at exactly the same time (by time stamps like 20240123161514), the two backups might conflict.

**Comment by directentis1** [comment]
The second chance I think is rarely possible, although not necessarily impossible.
Anyway, thank you for the update. 😇
