### ISSUE TITLE
[IDEA] Add JSON Configuration File

### ISSUE THREAD

**Issue by kookma** [hffqyd/tw5-server#4]
This is an elegant tiny server. Also, it is wonderful to serve a whole directory?
Thank you for your great work.

Like: https://github.com/K4rian/twserver-go can you add a configuration file (JSON)?

**Comment by hffqyd** [comment]
Good idea. I will add it in the next version. Thanks for your advice.

**Comment by hffqyd** [comment]
The feature has been added in v1.3.0.

**Comment by kookma** [comment]
Wonderful! Much appreciated!
