### ISSUE TITLE
What happens with backups autoclean when tw5server is started in the background? (autostart on login)

### ISSUE THREAD

**Issue by leoperbo** [hffqyd/tw5-server#5]
I'm transitioning from a browser-extension mechanism to tw5server for working with my TiddlyWikis. 

I made a script with a custom command to start tw5server and added an autostart entry in my desktop settings pointing to that script. Works like a charm.

Now, I'm wondering what happens with backups autoclean when tw5server is started in this way, where the corresponding prompt is not accessible.

Could there be an option to start tw5server with backups autoclean activated as default?

**Comment by hffqyd** [comment]
Nice idea. I will add it in the next version.

**Comment by hffqyd** [comment]
Added in v1.5.0, Thanks you.
