### ISSUE TITLE
Make file list sorted

### ISSUE THREAD

**Issue by johnwoltman** [hffqyd/tw5-server#7]
I have files named after dates like 2024-12-10, 2024-12-11, etc.  Right now tw5-server uses Nim's default sort order, which just depends on whatever the local file system does, so the files aren't actually list alphabetically or by date (at least on my Linux system).

I will do a PR with my solution to this.

**Comment by hffqyd** [comment]
Thank you, I've merged your code.

**Comment by johnwoltman** [comment]
Thanks for the quick response, have a happy new year!
